apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: kubereats # This MUST be in the same namespace as the MySQL pod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # This should match or be less than the PV's capacity
  # Optional selector to ensure binding to our specific PV
  selector:
    matchLabels:
      app: mysql
      # pv-label: mysql-volume # More specific binding if you use a unique label