apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: kubereats
spec:
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP