# k8s-manifests/4-stateful-services/mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubereats
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate # Important for stateful apps: prevents concurrent writes
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
            - name: MYSQL_DATABASE
              value: kubereats # Optional: create a default database
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql # MySQL's default data directory
#          livenessProbe:
#            exec:
#              command: [ "mysqladmin", "ping", "-h", "localhost", "-u$(MYSQL_ROOT_USERNAME)", "-p$(MYSQL_ROOT_PASSWORD)" ]
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 5
#          readinessProbe:
#            exec:
#              command: [ "mysql", "-h", "localhost", "-u$(MYSQL_ROOT_USERNAME)", "-p$(MYSQL_ROOT_PASSWORD)", "-e", "SELECT 1" ]
#            initialDelaySeconds: 5
#            periodSeconds: 5
#            timeoutSeconds: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc # Reference to the PVC we created
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: kubereats
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  # clusterIP: None # Headless service for stable DNS