# k8s-manifests/4-stateful-services/redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kubereats
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server"]
          args: ["--appendonly", "yes"] # Enable Redis persistence
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data # This is the path Redis writes its AOF file to.
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc # This line connects the Pod to the PVC we created.
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: kubereats
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None # Creates a headless service for direct pod discovery