# app-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: kubereats
data:
  database.url: "jdbc:mysql://mysql-service:3306/kubereats?allowPublicKeyRetrieval=true&useSSL=false"
  redis.host: "redis-service"